site_name: Test IBD-kg

docs_dir: md
site_dir: src

theme:
  name: material
  palette:
    - primary: indigo
    - accent: orange
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.footer

nav:
  - Home: index.md
  - About: about.md

# dark mode and auto dark/light mode don't work

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
