id: https://10-54-3-233.gcp.glicid.fr
name: ABRomicsKG
description: An antimicrobial resistance knowledge graph
prefixes:
  abromics: https://abromics.fr/
  sosa: http://www.w3.org/ns/sosa/
  ssn: http://www.w3.org/ns/ssn/
  schema: https://schema.org/
  rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  rdfs: http://www.w3.org/2000/01/rdf-schema#
  xsd: http://www.w3.org/2001/XMLSchema#
  obo: http://purl.obolibrary.org/obo/
  aro: http://purl.obolibrary.org/obo/ARO_
  go: http://purl.org/obo/owl/GO#
  uniprot: http://purl.uniprot.org/uniprot/
  uniprot-core: http://purl.uniprot.org/uniprot/core/
  geo: http://www.w3.org/2003/01/geo/wgs84_pos#
  sio: http://semanticscience.org/resource/
  skos: http://www.w3.org/2004/02/skos/core#
  prov: http://www.w3.org/ns/prov#
  foaf: http://xmlns.com/foaf/0.1/
  wdt: http://www.wikidata.org/prop/direct/
  ncit: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus
  ncbitaxon: http://purl.bioontology.org/ontology/NCBITAXON/
  envo: http://purl.obolibrary.org/obo/ENVO_
  uberon: http://purl.obolibrary.org/obo/UBERON_
  linkml: https://w3id.org/linkml/
imports:
  - linkml:types

classes:
  Sample:
    class_uri: [ prov:Entity, sio:001050, sio:000000 ]
    is_a: Sample
    description: A sample containing some sort of biological material
    attributes:
      host:
        slot_uri: uniprot-core:host
        description: Indicates the host specie the sample has been collected from. In the case of a sample collected in the environement, when there is no host specie, this field is should be ignored.
        multivalued: true
        range: CellularOrganisms
      wasDerivedFrom:
        slot_uri: prov:wasDerivedFrom
        description: Indicates the physical biological object that has been collected in the sample. It can be an anatomical structure, like a certain organ or a physical object such as soil for environemental samples. 
        multivalued: true
        range: SampleSource
      atLocation:
        slot_uri: prov:atLocation
        description: Indicates the region where the sample has been collected. It can be any sub class of wikidata region, including a specific country, state or any other wikidata geographical location.
        multivalued: true
        range: Region
      wasAttributedTo: 
        slot_uri: prov:wasAttributedTo
        description: Indicates the sequencer used to observe the biological sample leading to the generation of the raw sequence files from the biological sample or indicates the person that collected the biological sample
        multivalued: true
        range: [ Sensor, foaf:Person, prov:Agent ]
      inTaxon:
        slot_uri: obo:RO_0002162
        description: Indicates the taxons present in the sample.
        multivalued: true
        range: cellularOrganisms
      generatedAtTime:
        slot_uri: prov:generatedAtTime
        description: Indicates the exact time and date when the sample has been collected
        multivalued: false
        range: xsd:dateTime
      isSubjectOf:
        slot_uri: sio:000629
        description: Indicates the observations performed by a workflow on the biological samples' sequence files
        multivalued: true
        range: Observation
      isPartOf:
        slot_uri: sio:000068
        description: Indicates the type of the sample
        multivalued: false
        range: SampleType


  CellularOrganism:
    class_uri: ncbitaxon:131567
    is_a: Cellular organisms
    description: A cellular organism as defined in the NCBI taxonomy. All the bacterias, archeas and eukaryotas are considered to be cellular organisms

  SampleSource:
    class_uri: [ envo:00010483, uberon:0000465, ncit:C12434 ]
    description: A physical biological object, like an organ or a physical object such as soil for environement samples.

  Region:
    class_uri: wdt:Q82794
    is_a: Region
    description: 2D or 3D defined space on something, mainly in terrestrial and astrophysics sciences. It is any sub class of a region as defined in wikidata such as a specific country, state or any other wikidata geographical location. 

  Sensor:
    class_uri: sosa:Sensor
    is_a: Sensor
    description: The sequencer instrument that was used to generate the sequencing files from the biological sample
    attributes: 
      label:
        slot_uri: rdfs:label
        description: A string that represents the name of sequencer used to generate the sequencing files from the biological sample
        multivalued: false
        range: xsd:string


  SampleType:
    class_uri: prov:Entity
    is_a: Entity
    description: The type of a sample is represented by a single string being "human", "animal" or "enviromnental"
    attributes:
      label:
        slot_uri: rdfs:label
        description: A string that represents the type of sample ("human", "animal" or "environmental")
        multivalued: false
        range: xsd:string

  Observation:
    class_uri: [ sosa:Observation, sio:000000 ]
    is_a: Observation
    description: An observation made by a workflow on the sequencing files of a biological sample. The observation is one measure among many made the workflow on the sequencing files. 
    attributes:
      isAbout:
        slot_uri: sio:000332
        description: Indicates that the observation has been made about a certain sample
        multivalued: false
        range: Sample
      observedProperty:
        slot_uri: sosa:observedProperty
        description: A property of interest measured by the workflow on the seqencing file. It answers to the questions "what is the metric that has been measured ?". An example of observed property can be the a gene identity % or a specific quality metric for instance
        multivalued: false
        range: ObservableProperty
      ## Continue here


  ObservableProperty:
    class_uri: sosa:ObservableProperty
    ## Continue here
