## Nginx configurations

user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

include /etc/nginx/conf.d/*.conf;

events {
     worker_connections 1024;
}

http {

    include /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
 		      '$status $body_bytes_sent "$http_referer" '
		      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile on;
    keepalive_timeout  65;

    upstream virtuoso {
        ip_hash;
        server virtuoso:8890;
    }
    
    upstream $API_BASEPATH {
        ip_hash;
        server $API_BASEPATH:5000;
    }
    
    server {
    
        listen 80;
        server_name localhost;
    
        error_page 404 /errors/404/index.html;
    
        location /sparql {
            proxy_pass http://virtuoso;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
        }
    
        location /$API_BASEPATH {
            proxy_pass http://$API_BASEPATH;
        }
        
        location /errors/404/index.html {
            root /usr/share/nginx/html;
            internal;
        }
    
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }
    
    }

}
