PREFIX schema: <https://schema.org/>
PREFIX prov: <http://www.w3.org/ns/prov#>

INSERT {
    ?sample prov:wasDerivedFrom <http://purl.obolibrary.org/obo/ENVO_01001835> . 
} WHERE {
  ?sample schema:identifier "17-HoPe-P1-2" .
}
