PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX go: <http://purl.org/obo/owl/GO#>
PREFIX aro: <http://purl.obolibrary.org/obo/aro.owl#> # references to classes aro that are in the graph.. not really clean
PREFIX aro_o: <http://purl.obolibrary.org/obo/ARO_> # references to the classes of the aro ontology
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX schema: <https://schema.org/>
PREFIX abromics: <https://abromics.fr/>
PREFIX prov: <http://www.w3.org/ns/prov#>

# Q8: What are the strains resistant to specific class of antibiotics
#
# 
# Improvements: make the aro namespace common between the aro classes used in the graph and the 
#               aro namespace used in the aro ontology 
#
SELECT ?antibiotic WHERE {

   ?antibiotic rdfs:subClassOf aro_o:1000003 .

}
