PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX prov: <http://www.w3.org/ns/prov#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX abromics: <https://abromics.fr/>
PREFIX up: <http://purl.uniprot.org/core/> ## Ideal would be to have a link to ncbi taxon 
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#> ## this is the thesaurus not the NCBI taxon ontology 

SELECT ?personId ?email ?strainId ?collectedAt ?sampleType ?microorganism ?microorganismName ?hostSpecie ?hostSpecieName ?sampleSource ?location ?sequencer
WHERE { 
    ?sample prov:wasAttributedTo ?personId .
    ?personId rdf:type prov:Person .
    ?personId foaf:givenName "Claudine Médigue" .
    ?personId foaf:mbox ?email .

    ?sample abromics:strainId ?strainId .
    ?sample prov:generatedAtTime ?collectedAt .
    ?sample abromics:sampleType ?sampleType .

    ?sample abromics:microorganism ?microorganism .
    ?sample abromics:host ?hostSpecie .
    SERVICE <https://sparql.uniprot.org/> {
        ?microorganism up:scientificName ?microorganismName .
        ?hostSpecie up:scientificName ?hostSpecieName .
    }

    ?sample abromics:sampleSource ?sampleSource .
    

    ?sample prov:atLocation ?location .
    ?sample prov:wasGeneratedBy ?sequencer .
}
