PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX prov: <http://www.w3.org/ns/prov#> 
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX abromics: <https://abromics.fr/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?countryName (COUNT(?countryName) AS ?nbSamples)
WHERE {
    ?sample rdf:type sio:001050 .
    ?sample prov:atLocation ?country .

    # Send request to wikidata
    SERVICE <https://query.wikidata.org/sparql> {
      ?country rdfs:label ?countryName .
      FILTER(LANG(?countryName) = "en")
    }

} GROUP BY ?countryName
