PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX prov: <http://www.w3.org/ns/prov#> 
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX abromics: <https://abromics.fr/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX schema: <https://schema.org>

## This query contains an error when fetching the country
SELECT DISTINCT ?gene_name ?coverage ?sample WHERE {

    ?sample rdf:type sosa:FeatureOfInterest, sio:001050 ;
        prov:atLocation ?country .

    SERVICE <https://query.wikidata.org/sparql> {
      ?country rdfs:label ?countryName .
      FILTER(LANG(?countryName) = "en") .
      FILTER(?countryName = "France") .
    }

    ?coverage_prop rdf:type sosa:observableProperty ;
        rdfs:label "Coverage %" .

    ?observation sosa:hasObservableProperty ?coverage_prop ;
                 sosa:hasFeatureOfInterest ?sample ;
                 sosa:hasFeatureOfInterest ?gene ;
                 sosa:hasResult/sosa:hasSimpleResult ?coverage .

    ?gene rdf:type sosa:observableProperty, go:Gene ;
        rdfs:label ?gene_name .
             
}
