PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?label ?class
WHERE {
  VALUES ?topClassName { 
      "Anatomic Structure, System, or Substance"
  }
  ?topClass rdfs:label ?topClassName .
  ?class rdfs:subClassOf+ ?topClass .
  ?class rdfs:label ?label .
}
ORDER BY ?label
