PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX go: <http://purl.org/obo/owl/GO#>
PREFIX aro: <http://purl.obolibrary.org/obo/aro.owl#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX schema: <https://schema.org/>
PREFIX abromics: <https://abromics.fr/>
PREFIX prov: <http://www.w3.org/ns/prov#>

# Q6: What are the common antibiotic resistance genes present in a specific period of time 
#     and a list of all the samples where the resistance gene have been found
# 
SELECT ?gene_name (COUNT(DISTINCT ?res) as ?nb_occurences) (GROUP_CONCAT(DISTINCT ?sample; separator=", ") AS ?samples) WHERE {
   
   ?sample rdf:type sio:001050 ;
        schema:identifier ?sample_id ;
        prov:generatedAtTime ?collectedDate .

   ## collectedDate filtration
   FILTER (?collectedDate > "2019-10-23T00:00:00Z"^^xsd:dateTime && 
           ?collectedDate < "2020-03-23T00:00:00Z"^^xsd:dateTime)

   ?obs_prop rdf:type sosa:ObservableProperty ;
        rdfs:label "Resistance gene" .

   ?gene rdf:type go:Gene ;
        rdfs:label ?gene_name .

   ?res rdf:type sosa:Result ;
        sosa:hasSimpleResult ?resValue .

   ?observations sosa:hasObservableProperty ?obs_prop ;
        sosa:hasFeatureOfInterest ?gene ;
        sosa:hasFeatureOfInterest ?sample ;
        sosa:hasFeatureOfInterest ?strain ;
        sosa:hasResult ?res .

} 
GROUP BY ?gene_name ?resValue
ORDER BY DESC(?nb_occurences)
