PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ncbitaxon: <http://purl.obolibrary.org/obo/NCBITaxon_>
PREFIX uberon: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX obom: <https://data.bioontology.org/metadata/obo/>
PREFIX ro: <http://purl.obolibrary.org/obo/RO_>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX envo: <http://purl.obolibrary.org/obo/ENVO_>

## Get all the sample sources including the animal, human and environmental sample sources
## available 
##
SELECT DISTINCT ?class ?classLabel WHERE {
  {
    ?organs rdfs:subClassOf+ uberon:0000465 . ## uberon anatomical entity
    ?organs rdfs:label ?organLabels .
    BIND(?organs as ?class)
    BIND(?organLabels as ?classLabel)
  } UNION {
    ?class rdfs:subClassOf+ ncit:C12219 . ## ncit anatomical structure, system or substance
    MINUS {
      ?class rdfs:subClassOf+ ?excluded .
      VALUES ?excluded { ncit:C21599 ncit:C34070 } . ## Exclude micro anatomical structure and cell part
    }
    ?class rdfs:label ?classLabels .
    BIND(?class as ?class)
    BIND(?classLabels as ?classLabel)
  } UNION {
    ?envClass rdfs:subClassOf+ envo:00000428 . ## envo biome
    ?envClass rdfs:label ?envClassLabel .
    BIND(?envClass as ?class)
    BIND(?envClassLabel as ?classLabel)
  }
}
