PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ncbitaxon: <http://purl.obolibrary.org/obo/NCBITaxon_>
PREFIX uberon: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX envo: <http://purl.obolibrary.org/obo/ENVO_>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX sio: <http://semanticscience.org/resource/>

SELECT DISTINCT  ?class ?classLabel ?parentClass ?parentClassLabel (COUNT(?existingSamples) as ?nbOccurences) 
FROM <http://www.ontotext.com/explicit>
WHERE {
  { 
    ?class rdfs:subClassOf+ uberon:0000465 . 
  } UNION {
    ?class rdfs:subClassOf+ envo:00000428 .
  } UNION {
     ?class rdfs:subClassOf+ ncit:C12219 . ## ncit anatomical structure, system or substance
    MINUS {
      ?class rdfs:subClassOf+ ?excluded .
      VALUES ?excluded { ncit:C21599 ncit:C34070 } . ## Exclude micro anatomical structure and cell part
    }
  } UNION {
    ?existingSamples rdf:type sio:001050 .
    ?existingSamples prov:wasDerivedFrom ?class .
  }
  ?class rdfs:label ?classLabel .
  ?class rdfs:subClassOf ?parentClass .
  ?parentClass rdfs:label ?parentClassLabel .
} GROUP BY  ?class ?classLabel ?parentClass ?parentClassLabel
ORDER BY DESC(?nbOccurences)
