PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ncbitaxon: <http://purl.obolibrary.org/obo/NCBITaxon_>
PREFIX uberon: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX obom: <https://data.bioontology.org/metadata/obo/>
PREFIX ro: <http://purl.obolibrary.org/obo/RO_>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>

## Get all the anatomical structure from uberon and ncit excluding some categories 
## like all the subclass of the micro anatomical structure and cell part classes 
##
## ! This query doesn't work as is. It has a parameter to replace with a value
## 
## Parameters:
##  $specieName: string (example: "Homo sapiens")
##
SELECT DISTINCT ?specie ?class ?classLabel ?parentClass ?parentClassLabel (COUNT(?existingSamples) as ?nbOccurences) WHERE {
  {
    ?specie rdfs:label $specieName .
    ?organs ro:0002175 ?specie . ## ro:0002175 indicates the "present_in_taxon" ontology
    ?organs rdfs:subClassOf+ uberon:0000465 . ## The organ should be an anatomical structure (include all organs of the specie + blood ect)
    ?organs rdfs:label ?organLabels .
    BIND(?organs as ?class)
    BIND(?organLabels as ?classLabel)
  } UNION {
    ?class rdfs:subClassOf+ ncit:C12219 . ## ncit anatomical structure, system or substance
    MINUS {
      ?class rdfs:subClassOf+ ?excluded .
      VALUES ?excluded { ncit:C21599 ncit:C34070 } . ## Exclude micro anatomical structure and cell part
    }
    ?class rdfs:label ?classLabels .
    ?existingSamples prov:wasDerivedFrom ?class .
    BIND(?class as ?class)
    BIND(?classLabels as ?classLabel)
  }
  ?class rdfs:subClassOf ?parentClass .
  ?parentClass rdfs:label ?parentClassLabel .
  
} GROUP BY ?specie ?class ?classLabel ?parentClass ?parentClassLabel
ORDER BY DESC(?nbOccurences)
