PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ncbitaxon: <http://purl.obolibrary.org/obo/NCBITaxon_>
PREFIX uberon: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX obom: <https://data.bioontology.org/metadata/obo/>
PREFIX ro: <http://purl.obolibrary.org/obo/RO_>
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX sio: <http://semanticscience.org/resource/>

## Get all the anatomical structure from uberon and ncit excluding some categories 
## like all the subclasses of the micro anatomical structure and cell part classes 
## This query doesn't filter by specie names
##
## The count doesn't count all the samples it only counts one of them for 
## each sampleSource
SELECT DISTINCT ?class ?classLabel ?parentClass ?parentClassLabel (COUNT(?existingSamples) as ?nbOccurences) 
FROM <http://www.ontotext.com/explicit>
WHERE {
   {
    ?class rdfs:subClassOf+ uberon:0000465 .
  } UNION {
    ?class rdfs:subClassOf+ ncit:C12219 . ## ncit anatomical structure, system or substance
    MINUS {
      ?class rdfs:subClassOf+ ?excluded .
      VALUES ?excluded { ncit:C21599 ncit:C34070 } . ## Exclude micro anatomical structure and cell part
    }
  } UNION {
    ?existingSamples rdf:type sio:001050 .
    ?existingSamples prov:wasDerivedFrom ?class .
  }
 ?class rdfs:label ?classLabel .
  ?class rdfs:subClassOf ?parentClass .
  ?parentClass rdfs:label ?parentClassLabel .
} GROUP BY ?class ?classLabel ?parentClass ?parentClassLabel
ORDER BY DESC(?nbOccurences)

