PREFIX ncbitaxon: <http://purl.obolibrary.org/obo/NCBITaxon_>

SELECT ?class ?specieName WHERE {
  ?class rdfs:subClassOf+ ncbitaxon:2 . ## Getting all the sub class of the bacteria class
  ?class rdfs:label ?specieName .
}
