PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX abromics: <https://abromics.fr/>
PREFIX up: <http://purl.uniprot.org/core/> ## Ideal would be to have a link to ncbi taxon 
PREFIX ncit: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#> ## this is the thesaurus not the NCBI taxon ontology 
PREFIX sosa: <http://www.w3.org/ns/sosa/>

SELECT ?personId ?email ?strainId ?collectedAt ?sampleType ?microorganism ?hostSpecie ?sampleSource ?location ?sequencer (GROUP_CONCAT(?resultValue; separator=", ") AS ?resistantToAntibiotic)
WHERE { 
    ?sample prov:wasAttributedTo ?personId .
    ?personId rdf:type prov:Person .
    ?personId foaf:givenName "Claudine Médigue" .
    ?personId foaf:mbox ?email .

    ?sample abromics:strainId ?strainId .
    ?sample prov:generatedAtTime ?collectedAt .
    ?sample abromics:sampleType ?sampleType .

    ?sample abromics:microorganism ?microorganism .
    ?sample abromics:host ?hostSpecie .
    #SERVICE <https://sparql.uniprot.org> {
    #    ?microorganism up:scientificName ?microorganismName .
    #    ?hostSpecie up:scientificName ?hostSpecieName .
    #}

    ?sample abromics:sampleSource ?sampleSource .

    ?observationProp rdf:type sosa:ObservableProperty ;
        rdfs:label "Target antibiotic" .

    ?observation rdf:type sosa:Observation ;
        sosa:hasFeatureOfInterest ?sample ;
        sosa:hasObservableProperty ?observationProp ;
        sosa:hasResult ?result .

    ?result rdf:type sosa:Result ;
        sosa:hasSimpleResult ?resultValue .

    ?sample prov:atLocation ?location .
    ?sample prov:wasGeneratedBy ?sequencer .
}
GROUP BY ?personId ?email ?strainId ?collectedAt ?sampleType ?microorganism ?hostSpecie ?sampleSource ?location ?sequencer
