PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX prov: <http://www.w3.org/ns/prov#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?personId ?name ?email (COUNT(?sample) AS ?nbSamples)
WHERE {
    ?sample prov:wasAttributedTo ?personId .
    ?personId rdf:type prov:Person .
    ?personId foaf:givenName ?name .
    ?personId foaf:mbox ?email .
}
GROUP BY ?personId ?name ?email
