PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX prov: <http://www.w3.org/ns/prov#> 
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX abromics: <https://abromics.fr/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>

SELECT ?sample ?specie ?sampleType ?sampleSource ?uploaderName ?country WHERE {

    ?sample rdf:type sosa:FeatureOfInterest, sio:001050 ;
        abromics:microorganism ?specie ;
        prov:generatedAtTime ?genTime ;
        abromics:sampleType ?sampleType ;
        abromics:sampleSource ?sampleSource ;
        prov:wasAttributedTo ?person ;
        prov:atLocation ?country .

    ?person rdf:type prov:Agent ;
        foaf:givenName ?uploaderName .
             
}
