PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX schema: <https://schema.org/>


## Q1: Search for all antibiotic resistance genes in a specific biological sample 
## 
## This query allows get the sample having an identifier of "F1361", get all
## the observations associated with this sample and that have the observableProperty
## labeled "Resistance gene". 
##
## The query returns the simpleResults of these filtered observations. The simpleResults 
## are strings corresponding to the name of the resistance gene
SELECT DISTINCT ?gene_names WHERE {
    ?gene_name_prop a sosa:observableProperty ;
        rdfs:label "Resistance gene" .
                
    ?sample rdf:type sosa:FeatureOfInterest ;
        schema:identifier "F1361" . # Change the an other sample identifier to perform the search on an other sample
                
    ?observations sosa:hasObservableProperty ?gene_name_prop ;
        sosa:hasFeatureOfInterest ?sample ;
        sosa:hasResult/sosa:hasSimpleResult ?gene_names .
}
