PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>


## Q2: List k top antibiotic resistance genes by coverage
## 
## get all the samples present in the graph and as well as the observableProperty with the label "Coverage %"
## filter all the observations made on the samples for the specific coverage observableProperty and get the 
## value of the coverage for each observations. 
##
## The results are then returned in the coverage descending order (limited to 10 observations returned)  
SELECT DISTINCT ?gene_name ?coverage ?sample WHERE {

    ?sample rdf:type sosa:FeatureOfInterest, sio:001050 . ## sio:001050 corresponds to the sample entity of the SIO ontology (more information: https://www.ebi.ac.uk/ols4/search?q=sio%3A001050)

    ?coverage_prop rdf:type sosa:observableProperty ;
        rdfs:label "Coverage %" .

    ?observation sosa:hasObservableProperty ?coverage_prop ;
                 sosa:hasFeatureOfInterest ?sample ;
                 sosa:hasFeatureOfInterest ?gene ;
                 sosa:hasResult/sosa:hasSimpleResult ?coverage .

    ?gene rdf:type sosa:observableProperty, go:Gene ;
        rdfs:label ?gene_name .
             
} 
ORDER BY DESC(?coverage) 
LIMIT 10
